### ISSUE TITLE
Create site file with metadata

### ISSUE THREAD

**Issue by limnoliver** [USGS-R/national-flow-observations#15]
Would be helpful to have a site metadata file that has one row per site, including ID, lat/lon, site type, maybe n records from the data pull. Currently, we only have summaries of the "active" gages. This will be helpful for downstream projects like delaware-model-prep where we have to subset sites to a basin.

**Comment by padilla410** [comment]
Scratched the surface on this and it looks like David took care of it in PR #17 

Here's a snippet that verifies the inclusion of gages that are no longer active:

```r
> readRDS('10_nwis_pull/inout/nwis_dv_inventory.rds') %>% 
+   filter(site_no == '01012570') %>% 
+   select(c(1:6, 22:24))
    agency_cd  site_no                                    station_nm site_tp_cd dec_lat_va dec_long_va begin_date   end_date count_nu
432      USGS 01012570 FISH RIVER AT INLET FISH RIVER LAKE ME SITE 4         ST   46.78949   -68.77322 1982-07-15 1984-06-12      699
```
