### ISSUE TITLE
Switch repo credentialing from `dssecrets` to `saml2aws`

### ISSUE THREAD

**Issue by padilla410** [USGS-R/national-flow-observations#25]
Using `dssecrets` for AWS credentialing requires periodically updating the key. Using `saml2aws` does not have this requirement.

Documentation on the process from David: https://code.usgs.gov/wwatkins/data-storage-blog#credential-setup

[Teams discussion](https://teams.microsoft.com/l/message/19:264c78fefa624bcfaf46ac10b9305f5e@thread.skype/1647019420179?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&groupId=2651eb2e-8cf1-4caa-a084-0a11facc1d36&parentMessageId=1647019420179&teamName=GS-WMA%20IIDD%20Staff&channelName=Function%20-%20Data%20Pipelines&createdTime=1647019420179)

**Comment by lindsayplatt** [comment]
Fixed in #30!!!
