### ISSUE TITLE
Needs for gages-through-ages

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/national-flow-observations#3]
We need to get a count of unique active stream flow gages (meaning at least 355 days of data) for every year from 1890 to 2019. We also need to know the locations of those gages for each year.

[Here is the script](https://github.com/USGS-VIZLAB/gages-through-ages/blob/master/scripts/fetch/getData_siteRecords.R) that was originally used to pull this data.

**Comment by jread-usgs** [comment]
Another update we need on this too is to change the threshold of days of dv from 355 to 335

**Comment by lindsayplatt** [comment]
Sounds good 👍 Any specific reason behind these numbers? How do we determine 335?

**Comment by jread-usgs** [comment]
That is the number/threshold used in the reporting of gage counts to congress

**Comment by limnoliver** [comment]
@lindsayplatt -- I vaguely recall from our original conversation that you needed something in addition to discharge. Am I making that up, or do you have needs beyond parameterCd `00060`?

**Comment by lindsayplatt** [comment]
Hmmm I think it may be that we need instantaneous streamflow and not just daily since not all gages report out a daily value? Or was it that not all gages report out streamflow but have gage height?

**Comment by lindsayplatt** [comment]
Oh, I just remembered what you are thinking about (and updated my comment above). We have another vizzie (the river conditions animation) that uses the historic record of gage heights. It does not have an immediate need for a new data pull, so we can ignore that for now.

**Comment by limnoliver** [comment]
Copying over conversation from Teams for completion: Yes, from the temperature pipeline, we learned that not all sites are in DV, and so we will inventory both UV and DV, but only pull from UV what was missing in DV (because UV is big and slow, so only pull what we need).

**Comment by limnoliver** [comment]
Note - there were 589 sites in NWISuv that weren't represented in NWISdv.
